[Service]
User=mpd
Group=audio
# ensure the mpd user paths are set
Environment=XDG_RUNTIME_DIR=/run/user/${MPD_ID}
# might be safe to remove
BindPaths=/run/user/${MPD_ID}
# ensure the mpd user paths are reachable
# might be safe to remove
PrivateUsers=false
ProtectHome=false
