[Service]
User=mpd
Group=audio
# ensure the mpd user paths are set
Environment=XDG_RUNTIME_DIR=/run/user/${MPD_ID}
BindPaths=/run/user/${MPD_ID}
# ensure the mpd user paths are reachable
PrivateUsers=false
ProtectHome=false
