bind_to_address "any"
port "6600"
mixer_type "software"
music_directory "~/mpd/music"
db_file "~/mpd/database"
state_file "~/mpd/state"
restore_paused "yes"
auto_update "yes"
audio_output {
	type "pulse"
	name "Pink Noise - ${NODE_NAME}"
	mixer_type "software"
}
