bind_to_address "any"
port "6600"
mixer_type "software"
music_directory "/var/lib/mpd/music"
db_file "/var/lib/mpd/database"
audio_output {
	type "alsa"
	name "Pink Noise - ${NODE_NAME}"
	device "dmixer"
}
