wireplumber.settings = {
  device.routes.default-sink-volume = 0.9
}

monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.platform-bcm2835_audio.*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 100
      }
    }
  }
]
